# Generated by Django 5.2.6 on 2025-09-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_id", models.CharField(db_index=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
            ],
        ),
    ]
