# Generated by Django 5.2.6 on 2025-09-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_id", models.CharField(db_index=True, max_length=255)),
                ("task_name", models.CharField(max_length=255)),
                ("args", models.JSONField()),
                ("kwargs", models.JSONField()),
                ("sequence", models.IntegerField()),
            ],
        ),
    ]
