# Generated by Django 5.2.6 on 2025-09-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_api", "0002_workflowtask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowlog",
            name="payload",
        ),
        migrations.AddField(
            model_name="workflowlog",
            name="name",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workflowtask",
            name="task_name",
            field=models.TextField(),
        ),
    ]
