# Generated by Django 5.2.6 on 2025-09-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_api", "0003_remove_workflowlog_payload_workflowlog_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowlog",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
