# Generated by Django 5.2.6 on 2025-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_api", "0004_workflowlog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
